FROM eclipse-temurin:11 as jre-build
RUN $JAVA_HOME/bin/jlink \
        --verbose \
        --add-modules java.base,java.desktop,java.logging,java.management,java.naming,java.security.jgss,java.instrument,java.sql,jdk.unsupported,java.net.http,jdk.crypto.ec \
        --strip-debug \
        --no-man-pages \
        --no-header-files \
        --compress=2 \
        --output /opt/javaruntime

FROM debian:buster-slim as base
RUN apt-get update && apt-get install -y iputils-ping curl tcpdump && rm -rf /var/lib/apt/lists/*

ENV LC_ALL=C.UTF-8
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /opt/javaruntime $JAVA_HOME

ENTRYPOINT ["/bin/bash"]