#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE TABLE IF NOT EXISTS users
    (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        login text NOT NULL,
        role_id integer,
        salt text NOT NULL DEFAULT 'SERVICE',
        config jsonb NOT NULL,
        structure_id integer,
        name text NOT NULL DEFAULT 'SERVICE',
        enabled boolean NOT NULL DEFAULT true,
        CONSTRAINT users_pkey PRIMARY KEY (id),
        CONSTRAINT users_login_key UNIQUE (login)
    );

    CREATE TABLE IF NOT EXISTS refresh_sessions
    (
        user_id integer NOT NULL,
        refresh_token uuid NOT NULL,
        fingerprint text NOT NULL,
        expires_in timestamp with time zone NOT NULL,
        CONSTRAINT refresh_sessions_pkey PRIMARY KEY (refresh_token),
        CONSTRAINT refresh_sessions_user_id_fkey FOREIGN KEY (user_id)
            REFERENCES users (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
            NOT VALID
    );

    CREATE TABLE IF NOT EXISTS hashes
    (
        hash text NOT NULL
    );

    INSERT INTO users (login, config)
        VALUES
            ('admin', '{
                "smpo": {
                    "params": {
                     "ncBook": {
                       "signNc": {
                         "showActHistory": false
                       },
                       "showNormData": true,
                       "showAllNcBook": false
                     },
                     "mailSendingPeriod": {
                       "signNc": {
                         "signNc": 10,
                         "refuseNc": 10,
                         "firstLvlNotifyNc": 10,
                         "fullSignedNotifyNc": 10
                       }
                     }
                    },
                    "reports": [
                     1,
                     6
                    ],
                    "machines": [ 16, 17 ],
                    "roleName": "administrator",
                    "structureName": "pnppk"
                },
                "passport": {
                    "roles": [
                        "ROLE_ADMIN"
                    ],
                    "credentials_exp": 1672513199001
                }
            }'),
            ('zpm_operator', '{"smpo":{"params":{"ncBook":{"signNc":{"showActHistory":true},"showNormData":false,"showAllNcBook":true}},"roleId":2,"reports":[10],"machines":[16,17],"roleName":"operator","structureName":"zpm"}}');

    INSERT INTO hashes VALUES ('dummy');
EOSQL
