name: CI Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: JDK Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
